name: securecar_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: any

  # ! REMOVE: Dependências que devem ser substituidas por funções internas:
  pin_code_fields: ^8.0.1
  age_calculator: ^1.0.0
  email_validator: ^2.1.17
  


dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  very_good_analysis: ^5.0.0+1


flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
          